---
title: "Литературное программирование"
---

# Для кого этот курс

Целевой аудиторией мини курса "*Литературное программирование*" являются авторы, работа которых связана с созданием документов, презентирующих данные и их производные (иллюстрации и таблицы). 

- Научные статьи
- Научные отчеты
- Квалификационные работы 
- и многое другое...

Все упомянутые выше типы *литературных* произведений основаны на том, что автор на входе имеет *данные*, собранные в результате исследования, а на выходе *отформатированный текст*, в который вставлены рисунки и таблицы, отражающие информацию о данных.  

Процесс подготовки таких документов часто "бесструктурен" - подготовив исходные данные, автор начинает порождать из них рисунки и таблицы, которые обычно хранятся как отдельные сущности (отдельные файлы или отдельные листы или фрагменты листов в Excel). Обычно, параллельно происходит написание текста (как правило это происходит в редакторе типа Word), в который, по мере необходимости, вставляются рисунки и таблицы. Этот стиль опробован многими поколениями и кажется естественным и комфортным. Однако проблемы начинаются тогда, когда выясняется, что в первичных данных была какая-то ошибка или появились новые данные, которые изменят уже подготовленные рисунки и таблицы. Хорошо, если автор пунктуален и внес изменения во все производные от первичных данных документы. Часто ошибки проникают в финальные версии текста.

Избежать упомянутых проблем помогает философия *литературного программирования*. Идея этого подхода заключается в том, что основа основ, первичные данные, становятся фундаментом, частью *проекта*, на котором постепенно выстраивается текст, в который вставляются не сами рисунки (или таблицы), но  *алгоритмы*, порождающие эти *визуализации*. Сам же продукт, производимый в результате реализации проекта, в итоге, является результатом работы некоторой программы, алгоритма, который производит отформатированный документ (файл Word, html-страница, Power Point презентация, или документ в формате pdf). 

Алгоритмы описываются с помощью специализированных языков. В данном курсе мы освоим основы использования двух языков: *R* и *R Markdown*.  

Язык *R* позволит нам создать алгоритм, порождающий из первичных данных изящные рисунки и таблицы.

Язык *R Markdown* позволит описать алгоритм размещения материалов (заголовков, текстовых блоков, рисунков и таблиц) в финальном документе.  

# Минимальные требования для участников

- Базовые навуки рабты с компьютером: умение находить файлы, создавать папки, перамещать и копировать файлы и т.п.
- Базовые навыки работы в MS Office (Word, Excel). 
- Умение просматривать html-файлы через браузер (Firefox, Chrome, Edge, Opera)
- Умение устанавливать программы на компьютер из сети Интернет.
- Умение читать простейшие тексты на английском языке. Достаточно также умения переводить тексты электронным переводчиком. Лучшим электронным переводчиком в настоящее время является [DeepL](https://www.deepl.com/ru/translator)




# Структура курса

Курс состоит из пяти ступеней

### Ступень 1. Подготовка первичных данных

Вы научитесь 

- Избегать распространенных ошибок при набивке первичных данных.
- Создавать файлы с первичными данными в формате максимально удобном для их обработки (познакомитесь с философией опрятных данных, *tidy data*).



### Ступень 2. Основы языка *R*

Вы научитесь

- Инсталлировать язык *R* и программу *RStudio*, как среду для его использования. 
- Писать скрипты (записи алгоритмов) с использование функций языка *R*.
- Загружать первичные данные в среду *R*.

### Ступень 3. Использование языка *R* для построения рисунков.

Вы научитесь

- Создавать графики разного типа с использованием функций пакета "ggplot2".


### Ступень 4. Использование языка *R Markdown* для создания документов в формате html.

Вы научитесь

-  Создавать простейшие html-странички, содержащие отчет, включающий текст, таблицы с результатами обработки данных и рисунки, визуализирующие результаты.  


### Ступень 5. Использование языков *R* и *R Markdown* для создания документов в формате Word.

Вы научитесь 

- Создавать документы в формате Word, которые являются финальным продуктом.
- Создавать изящные таблицы любой сложности с использованием пакета "flextable"


